#!/usr/bin/env python3
"""Generate host-specific route catalogs from the canonical provider registry."""

from __future__ import annotations

import argparse
import copy
import json
from pathlib import Path
import sys
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "runtime"))

from model_routing.registry import RegistryError, load_registry  # noqa: E402


def _allowed_providers(registry: dict[str, Any], host_id: str) -> dict[str, Any]:
    return {
        provider_id: copy.deepcopy(provider)
        for provider_id, provider in registry["providers"].items()
        if host_id not in provider["nativeHosts"]
    }


def _display_routes(provider: dict[str, Any]) -> str:
    routes = list(provider["models"])
    routes.extend(family["example"] for family in provider["routeFamilies"])
    labels: list[str] = []
    fallback = provider["defaultModel"]["fallback"]
    source = provider["defaultModel"]["source"]
    if source == "codex-config":
        labels.append("configured Codex default")
    elif source == "kimi-config":
        labels.append("configured Kimi default")
    elif source == "registry" and fallback and fallback not in routes:
        routes.insert(0, fallback)
    labels.extend(f"`{route}`" for route in routes)
    return ", ".join(labels) or "any configured model"


def _display_effort(provider: dict[str, Any]) -> str:
    if provider["effort"]["kind"] == "none":
        return "not supported"
    values = provider["effort"]["values"]
    return ", ".join(f"`{value}`" for value in values) if values else "provider-defined"


def _runtime_references(provider: dict[str, Any]) -> str:
    references: list[str] = []
    for model in provider["models"].values():
        if model["runtimeReference"] not in references:
            references.append(model["runtimeReference"])
    for family in provider["routeFamilies"]:
        if family["runtimeReference"] not in references:
            references.append(family["runtimeReference"])
    return "<br>".join(
        f"[{reference.split('#', 1)[1]}]({reference.removeprefix('references/')})"
        for reference in references
    )


def render_markdown(registry: dict[str, Any], host_id: str) -> str:
    host = registry["hosts"][host_id]
    providers = _allowed_providers(registry, host_id)
    lines = [
        "# Generated Route Catalog",
        "",
        "<!-- Generated by tools/sync_routes.py; edit config/provider-registry.json instead. -->",
        "",
        f"Host: **{host['displayName']}**. Native providers omitted: "
        + (", ".join(f"`{item}`" for item in host["nativeProviders"]) or "none"),
        "",
        "| Provider | Shim | Known/default routes | Effort values | Runtime reference |",
        "|---|---|---|---|---|",
    ]
    for provider_id, provider in providers.items():
        lines.append(
            f"| `{provider_id}` | `~/.claude/scripts/{provider['shim']}` | "
            f"{_display_routes(provider)} | {_display_effort(provider)} | {_runtime_references(provider)} |"
        )
    lines.extend(
        [
            "",
            "Unknown model IDs remain pass-through when the provider CLI accepts them. This catalog is routing guidance, not a live provider availability claim.",
            "",
        ]
    )
    return "\n".join(lines)


def render_json(registry: dict[str, Any], host_id: str) -> str:
    payload = {
        "schemaVersion": registry["schemaVersion"],
        "host": host_id,
        "nativeProviders": registry["hosts"][host_id]["nativeProviders"],
        "providers": _allowed_providers(registry, host_id),
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def generated_files(registry: dict[str, Any]) -> dict[Path, str]:
    outputs: dict[Path, str] = {}
    for host_id, host in registry["hosts"].items():
        reference_dir = ROOT / host["packagePath"] / "skills" / "subagent-model-routing" / "references"
        outputs[reference_dir / "routes.generated.md"] = render_markdown(registry, host_id)
        outputs[reference_dir / "provider-registry.generated.json"] = render_json(registry, host_id)
    return outputs


def synchronize(*, check: bool) -> list[Path]:
    registry = load_registry(ROOT / "config" / "provider-registry.json")
    changed: list[Path] = []
    for path, content in generated_files(registry).items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        changed.append(path)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail instead of writing stale outputs")
    args = parser.parse_args(argv)
    try:
        changed = synchronize(check=args.check)
    except RegistryError as exc:
        print(f"cannot generate routes: {exc}", file=sys.stderr)
        return 1
    if changed:
        if args.check:
            for path in changed:
                print(f"stale generated route asset: {path.relative_to(ROOT)}", file=sys.stderr)
            return 1
        for path in changed:
            print(f"generated {path.relative_to(ROOT)}")
    else:
        print("generated route assets are current")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
